# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fort_search.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='fort_search.proto',
  package='PGo',
  syntax='proto3',
  serialized_pb=_b('\n\x11\x66ort_search.proto\x12\x03PGo\"U\n\x0f\x46ortSearchProto\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0b\n\x03lat\x18\x02 \x01(\x01\x12\x0c\n\x04long\x18\x03 \x01(\x01\x12\x0c\n\x04lat2\x18\x04 \x01(\x01\x12\r\n\x05long2\x18\x05 \x01(\x01\"\x93\x01\n\x12\x46ortSearchOutProto\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12.\n\x06result\x18\x02 \x01(\x0b\x32\x1e.PGo.FortSearchOutProto.Result\x1a<\n\x06Result\x12\x0b\n\x03ts1\x18\x01 \x01(\x04\x12\x0b\n\x03ts2\x18\x02 \x01(\x04\x12\x18\n\x05items\x18\x03 \x03(\x0b\x32\t.PGo.Item\"\x19\n\x04Item\x12\x11\n\ttimestamp\x18\x01 \x01(\x04\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_FORTSEARCHPROTO = _descriptor.Descriptor(
  name='FortSearchProto',
  full_name='PGo.FortSearchProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='PGo.FortSearchProto.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lat', full_name='PGo.FortSearchProto.lat', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='long', full_name='PGo.FortSearchProto.long', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lat2', full_name='PGo.FortSearchProto.lat2', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='long2', full_name='PGo.FortSearchProto.long2', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=111,
)


_FORTSEARCHOUTPROTO_RESULT = _descriptor.Descriptor(
  name='Result',
  full_name='PGo.FortSearchOutProto.Result',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ts1', full_name='PGo.FortSearchOutProto.Result.ts1', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ts2', full_name='PGo.FortSearchOutProto.Result.ts2', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='items', full_name='PGo.FortSearchOutProto.Result.items', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=201,
  serialized_end=261,
)

_FORTSEARCHOUTPROTO = _descriptor.Descriptor(
  name='FortSearchOutProto',
  full_name='PGo.FortSearchOutProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='PGo.FortSearchOutProto.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='result', full_name='PGo.FortSearchOutProto.result', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_FORTSEARCHOUTPROTO_RESULT, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=114,
  serialized_end=261,
)


_ITEM = _descriptor.Descriptor(
  name='Item',
  full_name='PGo.Item',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='PGo.Item.timestamp', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=263,
  serialized_end=288,
)

_FORTSEARCHOUTPROTO_RESULT.fields_by_name['items'].message_type = _ITEM
_FORTSEARCHOUTPROTO_RESULT.containing_type = _FORTSEARCHOUTPROTO
_FORTSEARCHOUTPROTO.fields_by_name['result'].message_type = _FORTSEARCHOUTPROTO_RESULT
DESCRIPTOR.message_types_by_name['FortSearchProto'] = _FORTSEARCHPROTO
DESCRIPTOR.message_types_by_name['FortSearchOutProto'] = _FORTSEARCHOUTPROTO
DESCRIPTOR.message_types_by_name['Item'] = _ITEM

FortSearchProto = _reflection.GeneratedProtocolMessageType('FortSearchProto', (_message.Message,), dict(
  DESCRIPTOR = _FORTSEARCHPROTO,
  __module__ = 'fort_search_pb2'
  # @@protoc_insertion_point(class_scope:PGo.FortSearchProto)
  ))
_sym_db.RegisterMessage(FortSearchProto)

FortSearchOutProto = _reflection.GeneratedProtocolMessageType('FortSearchOutProto', (_message.Message,), dict(

  Result = _reflection.GeneratedProtocolMessageType('Result', (_message.Message,), dict(
    DESCRIPTOR = _FORTSEARCHOUTPROTO_RESULT,
    __module__ = 'fort_search_pb2'
    # @@protoc_insertion_point(class_scope:PGo.FortSearchOutProto.Result)
    ))
  ,
  DESCRIPTOR = _FORTSEARCHOUTPROTO,
  __module__ = 'fort_search_pb2'
  # @@protoc_insertion_point(class_scope:PGo.FortSearchOutProto)
  ))
_sym_db.RegisterMessage(FortSearchOutProto)
_sym_db.RegisterMessage(FortSearchOutProto.Result)

Item = _reflection.GeneratedProtocolMessageType('Item', (_message.Message,), dict(
  DESCRIPTOR = _ITEM,
  __module__ = 'fort_search_pb2'
  # @@protoc_insertion_point(class_scope:PGo.Item)
  ))
_sym_db.RegisterMessage(Item)


# @@protoc_insertion_point(module_scope)
